// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Myapplication.Models;

namespace Myapplication.Migrations
{
    [DbContext(typeof(MyDBContextClass))]
    [Migration("20190927101745_yyzzkkll")]
    partial class yyzzkkll
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Myapplication.Models.EmployeeClass", b =>
                {
                    b.Property<int>("SerialNo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId");

                    b.Property<string>("EmployeeName")
                        .IsRequired();

                    b.Property<int>("EmployeeSalary");

                    b.HasKey("SerialNo");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            SerialNo = 1,
                            EmployeeId = 2,
                            EmployeeName = "Abhishek",
                            EmployeeSalary = 100000
                        },
                        new
                        {
                            SerialNo = 2,
                            EmployeeId = 4,
                            EmployeeName = "John",
                            EmployeeSalary = 100000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
